Feature/categories, images
Bletcher-Project/bletcher-back pull request #26
Opened 2020-08-25 07:00 UTC by kimdg1105

#### 관련 이슈 
#18 Category API Development
#19 [FEATURE] Images

#### 변경 사항  
- 기존 /services/post에 페이지네이션으로 분기된 get함수들을 통일했습니다.
- sevices/post 내에서 page,limit을 받아, 값이 있으면 페이지네이션, 없으면 모든 게시글을 가져옵니다.
- #18 에 작성한 API 추가
- 이미지 업로드, GET image path 추가 (#19 하면서 더 보완 예정)

#### PR Point 
 - postrouter 파일 내 get('/category/all/:id',...) 부분에서 `const nestedIdArr = Object.values(nestedId as Object);`에 대해 더 좋은 방향이 있을까요?

#### Reference 
https://drib.tech/programming/hierarchical-data-in-relational-databases
: 우리 디비의 모델입니다. 셀프 조인 및 모든 자식 노드 SELECT 등 필요한 쿼리들을 참고하였습니다. (추후 필요할 쿼리들도 많이 구현되어 있어 자주 참고할 것 같습니다.)

2020-08-25 08:40 UTC, KimKwon approved these changes
👍 
아마 스토리지 서버 연동되면 이미지 업로드 쪽 코드는 바뀌어야할 것 같습니다.ㅎㅎ

2020-08-25 08:40 UTC, KimKwon commented on src/services/image.ts
> +    // include: [
주석 지워야될듯용

2020-08-25 09:08 UTC, kimdg1105 commented on src/services/image.ts
> +    // include: [
감사합니다

2020-08-25 09:40 UTC, Seogeurim requested changes
/api/posts/category/all/:id 에서 데이터가 없을 경우 다음과 같이 뜹니당
![image](https://user-images.githubusercontent.com/22045163/91159046-7bba9e00-e702-11ea-9bde-63da667c9d71.png)

2020-08-25 09:40 UTC, Seogeurim commented on src/services/post.ts
> +    const allPost = await Post.findAll({
page, limit이 주어지지 않았을 때의 기본값은 offset 0, limit 10으로 두는 것은 어떤가요?
코드도 줄어들고 !
```suggestion
export const getPost = async (
  page: number = 1,
  limit: number = 10,
): Promise<Post[] | null> => {
  const allPost = await Post.findAll({
```

2020-08-25 09:40 UTC, Seogeurim commented on src/api/routes/posts.ts
> +          const getpost = getPostByCategoryId(v, null, null);
```suggestion
          const getpost = getPostByCategoryId(v);
```

2020-08-25 09:51 UTC, KimKwon commented on src/api/routes/posts.ts
> +      image_id: Joi.number().required(),
> 게시물을 업로드할 때 image_id는 어디에서 받아올 수 있나요?

프론트에서 이미지 업로드 Post 요청 후에 포스트 업로드 Post 요청을 보냅니다. 
이미지 업로드 Post는 업로드한 이미지의 image_id를 포함시켜 Response를 전달합니다.
이 image_id값을 Post request에 인자로 함께 보냅니다.

2020-08-25 10:21 UTC, Seogeurim commented on src/api/routes/posts.ts
> +      image_id: Joi.number().required(),
우와 딱 이해했으요 👍🏻👍🏻

2020-08-25 11:42 UTC, kimdg1105 commented on src/interfaces/image.ts
> +  height: number;
헉 그 때 얘기한게 삭제하는거였는데 아직 반영이 안된거같습니다. 수정할께용

2020-08-25 11:42 UTC, kimdg1105 commented on src/services/post.ts
> +    const allPost = await Post.findAll({
기본값 설정하는 방향으로 해보겠습니다!

2020-08-25 11:43 UTC, kimdg1105 commented on src/api/routes/posts.ts
> +          const getpost = getPostByCategoryId(v, null, null);
👍

2020-08-26 09:34 UTC, Seogeurim approved these changes
굳굳 !!! 카테고리 너무 신기해요 너무 너무 수고했습니당 ~~!~!

2020-08-26 10:05 UTC, merged