Feature/users
Bletcher-Project/bletcher-back pull request #44
Opened 2020-10-11 10:19 UTC by kimdg1105

#### 관련 이슈 
#42 User information modify

#### 변경 사항  
- 기존 User 테이블 속성들에 대한 값 수정 구현

#### PR Point 
 - 비밀번호 부분에서 원래 비밀번호와 바꾸려는 비밀번호가 같다면, 그대로 두게 하고, 변경할 때는 암호화 해서 저장되게 하였는데 저 부분이 매끄럽지 않은 것 같습니다. 조언 부탁드립니다.
 - id(nickname), pw 변경 후에도 토큰 값을 잘 가져오는 것을 확인했습니다.

#### Reference

2020-10-13 10:09 UTC, KimKwon commented on src/services/user.ts
> +  }
```javascript
 const encryptedPw = await bcrypt.hash(inputPassword, 10);
      existUser.update(
        {
          password: encryptedPw,
        },
        { where: { id } },
      );
    }
  }
```
이렇게 바꾸시면 좋을 것 같습니다~

2020-10-13 10:31 UTC, KimKwon requested changes

2020-10-13 10:31 UTC, KimKwon commented on src/services/user.ts
> +  }
```javascript
const inputPassword = userInfo.password;
  if (inputPassword) {
    const isPasswordMatch = passwordMatch(inputPassword, existUser);
    if (!isPasswordMatch) {
      const encryptedPw = await bcrypt.hash(inputPassword, 10);
      existUser.update(
        {
          password: encryptedPw,
        },
        { where: { id } },
      );
    }
  }
```

이렇게 수정하면 좋을 것 같습니다 👍

2020-10-13 10:45 UTC, Seogeurim reviewed
커멘트 달아보았습니당!!! 좋아요 👏🏻👏🏻👏🏻

2020-10-13 10:45 UTC, Seogeurim commented on src/api/routes/users.ts
> +  '/modify',
PUT 으로 Method만 다르니까 `/modify` -> `/`으로 해도 되지 않을까용?

2020-10-13 10:45 UTC, Seogeurim commented on src/services/user.ts
> +  if (inputPassword) {
inputPassword가 null일 수 있어서 if문이 있는 것인가용?

2020-10-13 10:45 UTC, Seogeurim commented on src/services/user.ts
> +  }
뭔가 password 확인, new password 이렇게 구분지어야 할 것 같은 느낌인데 (또 password 확인 안 되면 오류 보여주고) 제플린 보니까 이 부분이 디자인 플로우에 안 보이는 거죠?

2020-10-13 10:51 UTC, kimdg1105 commented on src/api/routes/users.ts
> +  '/modify',
아하 네 맞습니다! 수정하겠습니당

2020-10-13 10:54 UTC, kimdg1105 commented on src/services/user.ts
> +  }
넵 제플린에 비밀번호 변경에 대한 부분이 없는 것 같아요....

2020-10-13 11:13 UTC, kimdg1105 commented on src/services/user.ts
> +  if (inputPassword) {
넹 password 가 null로 들어오면 passwordMatch()로 검사하는 부분에서 에러가 생겨서 바디에 password가 있을 때만 패스워드 암호화해서 업데이트하게 하려구 저렇게 했습니다!

2020-10-13 13:26 UTC, Seogeurim commented on src/services/user.ts
> +  if (inputPassword) {
그럼 interface IUserModify에서 `password: string;`을 `password?: string;`으로 바꿔주지는 않아도 되는 것인지요?
아 라우터에서 받을 때는 길이 0인 string으로 들어오는 것인가요? 그럼 null은 어떻게 발생하나용?

2020-11-08 05:25 UTC, kimdg1105 commented on src/api/routes/users.ts
> +  '/modify',
수정했습니다!

2020-11-08 05:31 UTC, kimdg1105 commented on src/services/user.ts
> +  }
현재 비밀번호 (checkPassword) 확인 후, 수정동작 하도록 수정했습니다.

2020-11-15 06:56 UTC, Seogeurim approved these changes
어푸루부 !! 합니다 !

2020-11-15 06:58 UTC, KimKwon approved these changes
묵은... PR... 고생하셨습니다 👍

2020-11-15 06:58 UTC, merged